openapi: '3.0.3'
info:
  title: Financial Portfolio
  version: '1.0'
servers:
  - url: http://127.0.0.1:5000
paths:
  /financial-portfolio:
    post:
      responses:
        '200':
          description: OK
      parameters:
        - in: header
          name: x-api-host
          required: true
          schema:
            type: string
            example: finance-data.api.com
        - in: header
          name: x-api-key
          required: true
          schema:
            type: string
            example: YOUR_API_KEY
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            example: application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                portfolio_name:
                  type: string
                  example: Retirement Fund
                initial_balance:
                  type: number
                  example: 50000
