openapi: '3.0.3'
info:
  title: Currency Exchange
  version: '1.0'
servers:
  - url: http://127.0.0.1:5000
paths:
  /currency-exchange-rate:
    get:
      responses:
        '200':
          description: OK
      parameters:
        - in: header
          name: x-rapidapi-host
          required: true
          schema:
           type: string
           example: finance-data.api.com
        - in: header
          name: x-rapidapi-key
          required: true
          schema:
            type: string
            example: 1234567890
        - in: query
          name: from_symbol
          required: true
          schema:
            type: string
            example: USD
        - in: query
          name: to_symbol
          required: true
          schema:
            type: string
            example: NGN
        - in: query
          name: language
          required: false
          schema:
            type: string
            example: en
